# Generated by Django 4.0.4 on 2022-06-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodging',
            old_name='name',
            new_name='full_name',
        ),
    ]
