# Generated by Django 4.0.4 on 2022-06-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_rename_name_lodging_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodging',
            old_name='ammount_paid',
            new_name='amount_paid',
        ),
    ]
