# Generated by Django 4.0.4 on 2022-06-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_rename_ammount_paid_lodging_amount_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lodge',
        ),
        migrations.AlterField(
            model_name='lodging',
            name='room_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
